service: lambda-batch
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "batch:SubmitJob"
      Resource: "arn:aws:batch:*:*:*"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
    environment:
      TEST_ENV: "LLLLL1"
